# -*- coding: utf-8 -*-
"""ERROAYA-ASS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsYX4k-QcxENAFLfVT9OphI6oFWV8tC7
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)





"""Now, let's create a pair plot to visualize the relationships between all features, colored by the `species`."""

sns.pairplot(iris_df, hue='species', diag_kind='kde')
plt.suptitle('Pair Plot of Iris Dataset by Species', y=1.02) # Adjust suptitle position
plt.show()



import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Combine features (X) and target (y) into a single DataFrame for plotting
# Assuming X and y are already defined from previous steps
iris_df = pd.concat([X, y], axis=1)

# Rename target column for better readability in plots
iris_df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

# Display the first few rows of the combined DataFrame
display(iris_df.head())

"""Here is the pair plot of the Iris dataset, visualizing the relationships between all features, colored by the `species`."""

sns.pairplot(iris_df, hue='species', diag_kind='kde')
plt.suptitle('Pair Plot of Iris Dataset by Species', y=1.02) # Adjust suptitle position
plt.show()